console.log('[1,2,3].push: ', [1,2,3].push(4))
console.log('[1,2,3].pop: ', [1,2,3].pop())
console.log('[1,2,3].shift: ', [1,2,3].shift())
console.log('[1,2,3].unshift: ', [1,2,3].unshift(0))
console.log('[a,b].concat: ', ['a','b'].concat('c'))
console.log('[a,b,c].join: ', ['a','b','c'].join('-'))
console.log('[a,b,c].slice: ', ['a','b','c'].slice(1))
console.log('[a,b].indexOf: ', ['a','b'].indexOf('b'))
console.log('[a,b].includes: ', ['a','b'].includes('c'))
console.log('[1,2,3].find: ', [1,2,3].find((n) => n % 2 === 0))
console.log('[1,2,3].findIndex: ', [1,2,3].findIndex((n) => n % 2 !== 0))
console.log('[a,b].filter: ', ['a','b'].filter((n) => n != 'a'))
console.log('[1,2,3].reduce: ', [1,2,3].reduce((acc, cur) => acc + cur))
console.log('[1,2,3].every: ', [1,2,3].every((n) => n > 0))
console.log('[1,2,3].some: ', [1,2,3].some((n) => n < 0))
console.log('[1,2,3].reverse: ', [1,2,3].reverse())
console.log('[1,2,3].at: ', [1,2,3].at(-2))
